// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
//! This module provides terms for `Activity Streams 2.0` vocabulary
//!
//! ## Vocabulary:
//!
//! |||
//! |-----|-----|
//! |**Title**|Activity Streams 2.0|
//! |**Prefix**|as|
//! |**Namespace base IRI**|[https://www.w3.org/ns/activitystreams#](https://www.w3.org/ns/activitystreams#)|
//! |**Description**|Extended Activity Streams 2.0 Vocabulary|
//! |**Is defined by**|[https://raw.githubusercontent.com/zazuko/activitystreams/owl-fix/vocabulary/activitystreams2.owl](https://raw.githubusercontent.com/zazuko/activitystreams/owl-fix/vocabulary/activitystreams2.owl)|
//!

use crate::namespace;

namespace!(
    "https://www.w3.org/ns/activitystreams#",;
    Accept, "Accept",
    Activity, "Activity",
    Add, "Add",
    Announce, "Announce",
    Application, "Application",
    Arrive, "Arrive",
    Article, "Article",
    Audio, "Audio",
    Block, "Block",
    Collection, "Collection",
    CollectionPage, "CollectionPage",
    Create, "Create",
    Delete, "Delete",
    Dislike, "Dislike",
    Document, "Document",
    Event, "Event",
    Flag, "Flag",
    Follow, "Follow",
    Group, "Group",
    Ignore, "Ignore",
    Image, "Image",
    IntransitiveActivity, "IntransitiveActivity",
    Invite, "Invite",
    Join, "Join",
    Leave, "Leave",
    Like, "Like",
    Link, "Link",
    Listen, "Listen",
    Mention, "Mention",
    Move, "Move",
    Note, "Note",
    Object, "Object",
    Offer, "Offer",
    OrderedCollection, "OrderedCollection",
    OrderedCollectionPage, "OrderedCollectionPage",
    OrderedItems, "OrderedItems",
    Organization, "Organization",
    Page, "Page",
    Person, "Person",
    Place, "Place",
    Profile, "Profile",
    Question, "Question",
    Read, "Read",
    Reject, "Reject",
    Relationship, "Relationship",
    Remove, "Remove",
    Service, "Service",
    TentativeAccept, "TentativeAccept",
    TentativeReject, "TentativeReject",
    Tombstone, "Tombstone",
    Travel, "Travel",
    Undo, "Undo",
    Update, "Update",
    Video, "Video",
    View, "View",
    accuracy, "accuracy",
    actor, "actor",
    altitude, "altitude",
    anyOf, "anyOf",
    attachment, "attachment",
    attachments, "attachments",
    attributedTo, "attributedTo",
    audience, "audience",
    author, "author",
    bcc, "bcc",
    bto, "bto",
    cc, "cc",
    content, "content",
    context, "context",
    current, "current",
    deleted, "deleted",
    describes, "describes",
    downstreamDuplicates, "downstreamDuplicates",
    duration, "duration",
    endTime, "endTime",
    first, "first",
    formerType, "formerType",
    generator, "generator",
    height, "height",
    href, "href",
    hreflang, "hreflang",
    icon, "icon",
    image, "image",
    inReplyTo, "inReplyTo",
    instrument, "instrument",
    items, "items",
    last, "last",
    latitude, "latitude",
    location, "location",
    longitude, "longitude",
    mediaType, "mediaType",
    name, "name",
    next, "next",
    object, "object",
    objectType, "objectType",
    oneOf, "oneOf",
    origin, "origin",
    partOf, "partOf",
    prev, "prev",
    preview, "preview",
    provider, "provider",
    published, "published",
    radius, "radius",
    rating, "rating",
    rel, "rel",
    relationship, "relationship",
    replies, "replies",
    result, "result",
    startIndex, "startIndex",
    startTime, "startTime",
    subject, "subject",
    summary, "summary",
    tag, "tag",
    tags, "tags",
    target, "target",
    to, "to",
    totalItems, "totalItems",
    units, "units",
    updated, "updated",
    upstreamDuplicates, "upstreamDuplicates",
    url, "url",
    verb, "verb",
    width, "width"
);
