// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
//! This module provides terms for `The GoodRelations Vocabulary for Semantic Web-based E-Commerce` vocabulary
//!
//! ## Vocabulary:
//!
//! |||
//! |-----|-----|
//! |**Title**|The GoodRelations Vocabulary for Semantic Web-based E-Commerce|
//! |**Prefix**|gr|
//! |**Namespace base IRI**|[http://purl.org/goodrelations/v1#](http://purl.org/goodrelations/v1#)|
//! |**Description**|The GoodRelations ontology provides the vocabulary for annotating e-commerce offerings (1) to sell, lease, repair, dispose, or maintain commodity products and (2) to provide commodity services.  GoodRelations allows describing the relationship between (1) Web resources, (2) offerings made by those Web resources, (3) legal entities, (4) prices, (5) terms and conditions, and the aforementioned ontologies for products and services (6).   For more information, see http://purl.org/goodrelations/  Note: The base URI of GoodRelations is http://purl.org/goodrelations/v1. Please make sure you are only using element identifiers in this namespace, e.g. http://purl.org/goodrelations/v1#BusinessEntity. There may be copies of the ontology file on the Web which can be retrieved from other locations, BUT THOSE LOCATIONS MUST NOT BE USED AS THE BASIS OF IDENTIFIERS.  If you use GoodRelations for scientific purposes, please cite our paper:  Hepp, Martin: GoodRelations: An Ontology for Describing Products and Services Offers on the Web, Proceedings of the 16th International Conference on Knowledge Engineering and Knowledge Management (EKAW2008), September 29 - October 3, 2008, Acitrezza, Italy, Springer LNCS, Vol. 5268, pp. 332-347.  PDF at http://www.heppnetz.de/publications/|
//! |**Is defined by**|[http://purl.org/goodrelations/v1#](http://purl.org/goodrelations/v1#)|
//!

use crate::namespace;

namespace!(
    "http://purl.org/goodrelations/v1#",;
    ActualProductOrServiceInstance, "ActualProductOrServiceInstance",
    AmericanExpress, "AmericanExpress",
    Brand, "Brand",
    Business, "Business",
    BusinessEntity, "BusinessEntity",
    BusinessEntityType, "BusinessEntityType",
    BusinessFunction, "BusinessFunction",
    Buy, "Buy",
    ByBankTransferInAdvance, "ByBankTransferInAdvance",
    ByInvoice, "ByInvoice",
    COD, "COD",
    Cash, "Cash",
    CheckInAdvance, "CheckInAdvance",
    ConstructionInstallation, "ConstructionInstallation",
    DHL, "DHL",
    DayOfWeek, "DayOfWeek",
    DeliveryChargeSpecification, "DeliveryChargeSpecification",
    DeliveryMethod, "DeliveryMethod",
    DeliveryModeDirectDownload, "DeliveryModeDirectDownload",
    DeliveryModeFreight, "DeliveryModeFreight",
    DeliveryModeMail, "DeliveryModeMail",
    DeliveryModeOwnFleet, "DeliveryModeOwnFleet",
    DeliveryModeParcelService, "DeliveryModeParcelService",
    DeliveryModePickUp, "DeliveryModePickUp",
    DinersClub, "DinersClub",
    DirectDebit, "DirectDebit",
    Discover, "Discover",
    Dispose, "Dispose",
    Enduser, "Enduser",
    FederalExpress, "FederalExpress",
    Friday, "Friday",
    GoogleCheckout, "GoogleCheckout",
    Individual, "Individual",
    JCB, "JCB",
    Labor_BringIn, "Labor-BringIn",
    LeaseOut, "LeaseOut",
    License, "License",
    Location, "Location",
    LocationOfSalesOrServiceProvisioning, "LocationOfSalesOrServiceProvisioning",
    Maintain, "Maintain",
    MasterCard, "MasterCard",
    Monday, "Monday",
    N_Ary_Relations, "N-Ary-Relations",
    Offering, "Offering",
    OpeningHoursSpecification, "OpeningHoursSpecification",
    PartsAndLabor_BringIn, "PartsAndLabor-BringIn",
    PartsAndLabor_PickUp, "PartsAndLabor-PickUp",
    PayPal, "PayPal",
    PaySwarm, "PaySwarm",
    PaymentChargeSpecification, "PaymentChargeSpecification",
    PaymentMethod, "PaymentMethod",
    PaymentMethodCreditCard, "PaymentMethodCreditCard",
    PriceSpecification, "PriceSpecification",
    ProductOrService, "ProductOrService",
    ProductOrServiceModel, "ProductOrServiceModel",
    ProductOrServicesSomeInstancesPlaceholder, "ProductOrServicesSomeInstancesPlaceholder",
    ProvideService, "ProvideService",
    PublicHolidays, "PublicHolidays",
    PublicInstitution, "PublicInstitution",
    QualitativeValue, "QualitativeValue",
    QuantitativeValue, "QuantitativeValue",
    QuantitativeValueFloat, "QuantitativeValueFloat",
    QuantitativeValueInteger, "QuantitativeValueInteger",
    Repair, "Repair",
    Reseller, "Reseller",
    Saturday, "Saturday",
    Sell, "Sell",
    SomeItems, "SomeItems",
    Sunday, "Sunday",
    Thursday, "Thursday",
    Tuesday, "Tuesday",
    TypeAndQuantityNode, "TypeAndQuantityNode",
    UPS, "UPS",
    UnitPriceSpecification, "UnitPriceSpecification",
    VISA, "VISA",
    WarrantyPromise, "WarrantyPromise",
    WarrantyScope, "WarrantyScope",
    Wednesday, "Wednesday",
    acceptedPaymentMethods, "acceptedPaymentMethods",
    addOn, "addOn",
    advanceBookingRequirement, "advanceBookingRequirement",
    amountOfThisGood, "amountOfThisGood",
    appliesToDeliveryMethod, "appliesToDeliveryMethod",
    appliesToPaymentMethod, "appliesToPaymentMethod",
    availabilityEnds, "availabilityEnds",
    availabilityStarts, "availabilityStarts",
    availableAtOrFrom, "availableAtOrFrom",
    availableDeliveryMethods, "availableDeliveryMethods",
    billingIncrement, "billingIncrement",
    category, "category",
    closes, "closes",
    color, "color",
    condition, "condition",
    datatypeProductOrServiceProperty, "datatypeProductOrServiceProperty",
    deliveryLeadTime, "deliveryLeadTime",
    depth, "depth",
    description, "description",
    displayPosition, "displayPosition",
    durationOfWarrantyInMonths, "durationOfWarrantyInMonths",
    eligibleCustomerTypes, "eligibleCustomerTypes",
    eligibleDuration, "eligibleDuration",
    eligibleRegions, "eligibleRegions",
    eligibleTransactionVolume, "eligibleTransactionVolume",
    equal, "equal",
    greater, "greater",
    greaterOrEqual, "greaterOrEqual",
    hasBrand, "hasBrand",
    hasBusinessFunction, "hasBusinessFunction",
    hasCurrency, "hasCurrency",
    hasCurrencyValue, "hasCurrencyValue",
    hasDUNS, "hasDUNS",
    hasEAN_UCC_13, "hasEAN_UCC-13",
    hasEligibleQuantity, "hasEligibleQuantity",
    hasGTIN_14, "hasGTIN-14",
    hasGTIN_8, "hasGTIN-8",
    hasGlobalLocationNumber, "hasGlobalLocationNumber",
    hasISICv4, "hasISICv4",
    hasInventoryLevel, "hasInventoryLevel",
    hasMPN, "hasMPN",
    hasMakeAndModel, "hasMakeAndModel",
    hasManufacturer, "hasManufacturer",
    hasMaxCurrencyValue, "hasMaxCurrencyValue",
    hasMaxValue, "hasMaxValue",
    hasMaxValueFloat, "hasMaxValueFloat",
    hasMaxValueInteger, "hasMaxValueInteger",
    hasMinCurrencyValue, "hasMinCurrencyValue",
    hasMinValue, "hasMinValue",
    hasMinValueFloat, "hasMinValueFloat",
    hasMinValueInteger, "hasMinValueInteger",
    hasNAICS, "hasNAICS",
    hasNext, "hasNext",
    hasOpeningHoursDayOfWeek, "hasOpeningHoursDayOfWeek",
    hasOpeningHoursSpecification, "hasOpeningHoursSpecification",
    hasPOS, "hasPOS",
    hasPrevious, "hasPrevious",
    hasPriceSpecification, "hasPriceSpecification",
    hasStockKeepingUnit, "hasStockKeepingUnit",
    hasUnitOfMeasurement, "hasUnitOfMeasurement",
    hasValue, "hasValue",
    hasValueFloat, "hasValueFloat",
    hasValueInteger, "hasValueInteger",
    hasWarrantyPromise, "hasWarrantyPromise",
    hasWarrantyScope, "hasWarrantyScope",
    height, "height",
    includes, "includes",
    includesObject, "includesObject",
    isAccessoryOrSparePartFor, "isAccessoryOrSparePartFor",
    isConsumableFor, "isConsumableFor",
    isListPrice, "isListPrice",
    isSimilarTo, "isSimilarTo",
    isVariantOf, "isVariantOf",
    legalName, "legalName",
    lesser, "lesser",
    lesserOrEqual, "lesserOrEqual",
    name, "name",
    nonEqual, "nonEqual",
    offers, "offers",
    opens, "opens",
    owns, "owns",
    predecessorOf, "predecessorOf",
    priceType, "priceType",
    qualitativeProductOrServiceProperty, "qualitativeProductOrServiceProperty",
    quantitativeProductOrServiceProperty, "quantitativeProductOrServiceProperty",
    relatedWebService, "relatedWebService",
    seeks, "seeks",
    serialNumber, "serialNumber",
    successorOf, "successorOf",
    taxID, "taxID",
    typeOfGood, "typeOfGood",
    validFrom, "validFrom",
    validThrough, "validThrough",
    valueAddedTaxIncluded, "valueAddedTaxIncluded",
    valueReference, "valueReference",
    vatID, "vatID",
    weight, "weight",
    width, "width"
);
