// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
use crate::namespace;

namespace!(
    "http://www.w3.org/2011/http#",;
    Connection, "Connection",
    EntityHeader, "EntityHeader",
    GeneralHeader, "GeneralHeader",
    HeaderElement, "HeaderElement",
    HeaderName, "HeaderName",
    Message, "Message",
    MessageHeader, "MessageHeader",
    Method, "Method",
    Parameter, "Parameter",
    Request, "Request",
    RequestHeader, "RequestHeader",
    Response, "Response",
    ResponseHeader, "ResponseHeader",
    StatusCode, "StatusCode",
    absolutePath, "absolutePath",
    absoluteURI, "absoluteURI",
    authority, "authority",
    body, "body",
    connectionAuthority, "connectionAuthority",
    elementName, "elementName",
    elementValue, "elementValue",
    fieldName, "fieldName",
    fieldValue, "fieldValue",
    hdrName, "hdrName",
    headerElements, "headerElements",
    headers, "headers",
    httpVersion, "httpVersion",
    methodName, "methodName",
    mthd, "mthd",
    paramName, "paramName",
    paramValue, "paramValue",
    params, "params",
    reasonPhrase, "reasonPhrase",
    requestURI, "requestURI",
    requests, "requests",
    resp, "resp",
    sc, "sc",
    statusCodeNumber, "statusCodeNumber",
    statusCodeValue, "statusCodeValue"
);