// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
//! This module provides terms for `ical` vocabulary
//!
//! ## Vocabulary:
//!
//! |||
//! |-----|-----|
//! |**Title**||
//! |**Prefix**|ical|
//! |**Namespace base IRI**|[http://www.w3.org/2002/12/cal/icaltzd#](http://www.w3.org/2002/12/cal/icaltzd#)|
//! |**Description**||
//! |**Is defined by**|[http://www.w3.org/2002/12/cal/icaltzd.rdf](http://www.w3.org/2002/12/cal/icaltzd.rdf)|
//!

use crate::namespace;

namespace!(
    "http://www.w3.org/2002/12/cal/icaltzd#",;
    DomainOf_rrule, "DomainOf_rrule",
    List_of_Float, "List_of_Float",
    Valarm, "Valarm",
    Value_CAL_ADDRESS, "Value_CAL-ADDRESS",
    Value_DATE, "Value_DATE",
    Value_DATE_TIME, "Value_DATE-TIME",
    Value_DURATION, "Value_DURATION",
    Value_PERIOD, "Value_PERIOD",
    Value_RECUR, "Value_RECUR",
    Vcalendar, "Vcalendar",
    Vevent, "Vevent",
    Vfreebusy, "Vfreebusy",
    Vjournal, "Vjournal",
    Vtimezone, "Vtimezone",
    Vtodo, "Vtodo",
    X_, "X-",
    action, "action",
    altrep, "altrep",
    attach, "attach",
    attendee, "attendee",
    byday, "byday",
    byhour, "byhour",
    byminute, "byminute",
    bymonth, "bymonth",
    bysecond, "bysecond",
    bysetpos, "bysetpos",
    byweekno, "byweekno",
    byyearday, "byyearday",
    calAddress, "calAddress",
    calscale, "calscale",
    categories, "categories",
    class, "class",
    cn, "cn",
    comment, "comment",
    completed, "completed",
    component, "component",
    contact, "contact",
    count, "count",
    created, "created",
    cutype, "cutype",
    dateTime, "dateTime",
    daylight, "daylight",
    delegatedFrom, "delegatedFrom",
    delegatedTo, "delegatedTo",
    description, "description",
    dir, "dir",
    dtend, "dtend",
    dtstamp, "dtstamp",
    dtstart, "dtstart",
    due, "due",
    duration, "duration",
    encoding, "encoding",
    exdate, "exdate",
    exrule, "exrule",
    fbtype, "fbtype",
    fmttype, "fmttype",
    freebusy, "freebusy",
    freq, "freq",
    geo, "geo",
    interval, "interval",
    language, "language",
    lastModified, "lastModified",
    location, "location",
    member, "member",
    method, "method",
    organizer, "organizer",
    partstat, "partstat",
    percentComplete, "percentComplete",
    priority, "priority",
    prodid, "prodid",
    range, "range",
    rdate, "rdate",
    recurrenceId, "recurrenceId",
    related, "related",
    relatedTo, "relatedTo",
    reltype, "reltype",
    repeat, "repeat",
    requestStatus, "requestStatus",
    resources, "resources",
    role, "role",
    rrule, "rrule",
    rsvp, "rsvp",
    sentBy, "sentBy",
    sequence, "sequence",
    standard, "standard",
    status, "status",
    summary, "summary",
    transp, "transp",
    trigger, "trigger",
    tzid, "tzid",
    tzname, "tzname",
    tzoffsetfrom, "tzoffsetfrom",
    tzoffsetto, "tzoffsetto",
    tzurl, "tzurl",
    uid, "uid",
    until, "until",
    url, "url",
    version, "version",
    wkst, "wkst"
);
