// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
use crate::namespace;

namespace!(
    "http://lexvo.org/ontology#",;
    CJKRadical, "CJKRadical",
    Character, "Character",
    GeographicRegion, "GeographicRegion",
    Language, "Language",
    Script, "Script",
    Term, "Term",
    broader, "broader",
    characterRadical, "characterRadical",
    containsCharacter, "containsCharacter",
    evokes, "evokes",
    hasCharacterComponent, "hasCharacterComponent",
    hasMember, "hasMember",
    inScript, "inScript",
    involvedIn, "involvedIn",
    involves, "involves",
    isFocusOf, "isFocusOf",
    iso15924Alphacode, "iso15924Alphacode",
    iso639P1Code, "iso639P1Code",
    iso639P2BCode, "iso639P2BCode",
    iso639P2TCode, "iso639P2TCode",
    iso639P3Code, "iso639P3Code",
    iso639P5Code, "iso639P5Code",
    label, "label",
    language, "language",
    lexicalCategory, "lexicalCategory",
    marcCode, "marcCode",
    means, "means",
    memberOf, "memberOf",
    narrower, "narrower",
    nearlySameAs, "nearlySameAs",
    nonRadicalStrokes, "nonRadicalStrokes",
    representedBy, "representedBy",
    represents, "represents",
    scriptFor, "scriptFor",
    somewhatSameAs, "somewhatSameAs",
    strength, "strength",
    strictlySameAs, "strictlySameAs",
    translation, "translation",
    usedIn, "usedIn",
    usesScript, "usesScript",
    variant, "variant"
);