// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
//! This module provides terms for `ma` vocabulary
//!
//! ## Vocabulary:
//!
//! |||
//! |-----|-----|
//! |**Title**||
//! |**Prefix**|ma|
//! |**Namespace base IRI**|[http://www.w3.org/ns/ma-ont#](http://www.w3.org/ns/ma-ont#)|
//! |**Description**|Created by Tobias Buerger, Jean Pierre Evain and Pierre-Antoine Champin with the RDFS Taskforce within the W3C Media Annotation Working Group.|
//! |**Is defined by**|[http://www.w3.org/ns/ma-ont#](http://www.w3.org/ns/ma-ont#)|
//!

use crate::namespace;

namespace!(
    "http://www.w3.org/ns/ma-ont#",;
    Agent, "Agent",
    AudioTrack, "AudioTrack",
    Collection, "Collection",
    DataTrack, "DataTrack",
    Image, "Image",
    Location, "Location",
    MediaFragment, "MediaFragment",
    MediaResource, "MediaResource",
    Organisation, "Organisation",
    Person, "Person",
    Rating, "Rating",
    TargetAudience, "TargetAudience",
    Track, "Track",
    VideoTrack, "VideoTrack",
    alternativeTitle, "alternativeTitle",
    averageBitRate, "averageBitRate",
    collectionName, "collectionName",
    copyright, "copyright",
    createdIn, "createdIn",
    creationDate, "creationDate",
    date, "date",
    depictsFictionalLocation, "depictsFictionalLocation",
    description, "description",
    duration, "duration",
    editDate, "editDate",
    features, "features",
    fragmentName, "fragmentName",
    frameHeight, "frameHeight",
    frameRate, "frameRate",
    frameSizeUnit, "frameSizeUnit",
    frameWidth, "frameWidth",
    hasAccessConditions, "hasAccessConditions",
    hasAudioDescription, "hasAudioDescription",
    hasCaptioning, "hasCaptioning",
    hasChapter, "hasChapter",
    hasClassification, "hasClassification",
    hasClassificationSystem, "hasClassificationSystem",
    hasCompression, "hasCompression",
    hasContributedTo, "hasContributedTo",
    hasContributor, "hasContributor",
    hasCopyrightOver, "hasCopyrightOver",
    hasCreated, "hasCreated",
    hasCreator, "hasCreator",
    hasFormat, "hasFormat",
    hasFragment, "hasFragment",
    hasGenre, "hasGenre",
    hasKeyword, "hasKeyword",
    hasLanguage, "hasLanguage",
    hasLocationCoordinateSystem, "hasLocationCoordinateSystem",
    hasMember, "hasMember",
    hasNamedFragment, "hasNamedFragment",
    hasPermissions, "hasPermissions",
    hasPolicy, "hasPolicy",
    hasPublished, "hasPublished",
    hasPublisher, "hasPublisher",
    hasRating, "hasRating",
    hasRatingSystem, "hasRatingSystem",
    hasRelatedImage, "hasRelatedImage",
    hasRelatedLocation, "hasRelatedLocation",
    hasRelatedResource, "hasRelatedResource",
    hasSigning, "hasSigning",
    hasSource, "hasSource",
    hasSubtitling, "hasSubtitling",
    hasTargetAudience, "hasTargetAudience",
    hasTrack, "hasTrack",
    isCaptioningOf, "isCaptioningOf",
    isChapterOf, "isChapterOf",
    isCopyrightedBy, "isCopyrightedBy",
    isCreationLocationOf, "isCreationLocationOf",
    isFictionalLocationDepictedIn, "isFictionalLocationDepictedIn",
    isFragmentOf, "isFragmentOf",
    isImageRelatedTo, "isImageRelatedTo",
    isLocationRelatedTo, "isLocationRelatedTo",
    isMemberOf, "isMemberOf",
    isNamedFragmentOf, "isNamedFragmentOf",
    isProvidedBy, "isProvidedBy",
    isRatingOf, "isRatingOf",
    isRelatedTo, "isRelatedTo",
    isSigningOf, "isSigningOf",
    isSourceOf, "isSourceOf",
    isTargetAudienceOf, "isTargetAudienceOf",
    isTrackOf, "isTrackOf",
    locationAltitude, "locationAltitude",
    locationLatitude, "locationLatitude",
    locationLongitude, "locationLongitude",
    locationName, "locationName",
    locator, "locator",
    mainOriginalTitle, "mainOriginalTitle",
    numberOfTracks, "numberOfTracks",
    playsIn, "playsIn",
    provides, "provides",
    ratingScaleMax, "ratingScaleMax",
    ratingScaleMin, "ratingScaleMin",
    ratingValue, "ratingValue",
    recordDate, "recordDate",
    releaseDate, "releaseDate",
    samplingRate, "samplingRate",
    title, "title",
    trackName, "trackName"
);
