// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
#[cfg(feature = "ns-cert")]
pub mod cert;
#[cfg(feature = "ns-gold")]
pub mod gold;
#[cfg(feature = "ns-lexvo")]
pub mod lexvo;
#[cfg(feature = "ns-lime")]
pub mod lime;
#[cfg(feature = "ns-oidc")]
pub mod oidc;
#[cfg(feature = "ns-ontolex")]
pub mod ontolex;
#[cfg(feature = "ns-pim")]
pub mod pim;
#[cfg(feature = "ns-solid")]
pub mod solid;
#[cfg(feature = "ns-solid_protocol_0_9")]
pub mod solid_protocol_0_9;
#[cfg(feature = "ns-spec")]
pub mod spec;
#[cfg(feature = "ns-stat")]
pub mod stat;
#[cfg(feature = "ns-vartrans")]
pub mod vartrans;
#[cfg(feature = "ns-acl")]
pub mod acl;
#[cfg(feature = "ns-as_")]
pub mod as_;
#[cfg(feature = "ns-bibo")]
pub mod bibo;
#[cfg(feature = "ns-cc")]
pub mod cc;
#[cfg(feature = "ns-cnt")]
pub mod cnt;
#[cfg(feature = "ns-constant")]
pub mod constant;
#[cfg(feature = "ns-csvw")]
pub mod csvw;
#[cfg(feature = "ns-dash")]
pub mod dash;
#[cfg(feature = "ns-dbo")]
pub mod dbo;
#[cfg(feature = "ns-dc11")]
pub mod dc11;
#[cfg(feature = "ns-dcam")]
pub mod dcam;
#[cfg(feature = "ns-dcat")]
pub mod dcat;
#[cfg(feature = "ns-dcmitype")]
pub mod dcmitype;
#[cfg(feature = "ns-dcterms")]
pub mod dcterms;
#[cfg(feature = "ns-discipline")]
pub mod discipline;
#[cfg(feature = "ns-doap")]
pub mod doap;
#[cfg(feature = "ns-dpv")]
pub mod dpv;
#[cfg(feature = "ns-dqv")]
pub mod dqv;
#[cfg(feature = "ns-dtype")]
pub mod dtype;
#[cfg(feature = "ns-duv")]
pub mod duv;
#[cfg(feature = "ns-earl")]
pub mod earl;
#[cfg(feature = "ns-ebucore")]
pub mod ebucore;
#[cfg(feature = "ns-exif")]
pub mod exif;
#[cfg(feature = "ns-foaf")]
pub mod foaf;
#[cfg(feature = "ns-frbr")]
pub mod frbr;
#[cfg(feature = "ns-geo")]
pub mod geo;
#[cfg(feature = "ns-geof")]
pub mod geof;
#[cfg(feature = "ns-geor")]
pub mod geor;
#[cfg(feature = "ns-gn")]
pub mod gn;
#[cfg(feature = "ns-gr")]
pub mod gr;
#[cfg(feature = "ns-grddl")]
pub mod grddl;
#[cfg(feature = "ns-gs1")]
pub mod gs1;
#[cfg(feature = "ns-gtfs")]
pub mod gtfs;
#[cfg(feature = "ns-http")]
pub mod http;
#[cfg(feature = "ns-hydra")]
pub mod hydra;
#[cfg(feature = "ns-ical")]
pub mod ical;
#[cfg(feature = "ns-ldp")]
pub mod ldp;
#[cfg(feature = "ns-locn")]
pub mod locn;
#[cfg(feature = "ns-lvont")]
pub mod lvont;
#[cfg(feature = "ns-ma")]
pub mod ma;
#[cfg(feature = "ns-oa")]
pub mod oa;
#[cfg(feature = "ns-og")]
pub mod og;
#[cfg(feature = "ns-org")]
pub mod org;
#[cfg(feature = "ns-owl")]
pub mod owl;
#[cfg(feature = "ns-prefix")]
pub mod prefix;
#[cfg(feature = "ns-prov")]
pub mod prov;
#[cfg(feature = "ns-qb")]
pub mod qb;
#[cfg(feature = "ns-qkdv")]
pub mod qkdv;
#[cfg(feature = "ns-quantitykind")]
pub mod quantitykind;
#[cfg(feature = "ns-qudt")]
pub mod qudt;
#[cfg(feature = "ns-rdau")]
pub mod rdau;
#[cfg(feature = "ns-rdf")]
pub mod rdf;
#[cfg(feature = "ns-rdfa")]
pub mod rdfa;
#[cfg(feature = "ns-rdfs")]
pub mod rdfs;
#[cfg(feature = "ns-rico")]
pub mod rico;
#[cfg(feature = "ns-rr")]
pub mod rr;
#[cfg(feature = "ns-rss")]
pub mod rss;
#[cfg(feature = "ns-schema")]
pub mod schema;
#[cfg(feature = "ns-sd")]
pub mod sd;
#[cfg(feature = "ns-sdmx")]
pub mod sdmx;
#[cfg(feature = "ns-sem")]
pub mod sem;
#[cfg(feature = "ns-sh")]
pub mod sh;
#[cfg(feature = "ns-shex")]
pub mod shex;
#[cfg(feature = "ns-sioc")]
pub mod sioc;
#[cfg(feature = "ns-skos")]
pub mod skos;
#[cfg(feature = "ns-skosxl")]
pub mod skosxl;
#[cfg(feature = "ns-sosa")]
pub mod sosa;
#[cfg(feature = "ns-sou")]
pub mod sou;
#[cfg(feature = "ns-ssn")]
pub mod ssn;
#[cfg(feature = "ns-test")]
pub mod test;
#[cfg(feature = "ns-time")]
pub mod time;
#[cfg(feature = "ns-unit")]
pub mod unit;
#[cfg(feature = "ns-vaem")]
pub mod vaem;
#[cfg(feature = "ns-vann")]
pub mod vann;
#[cfg(feature = "ns-vcard")]
pub mod vcard;
#[cfg(feature = "ns-void")]
pub mod void;
#[cfg(feature = "ns-vs")]
pub mod vs;
#[cfg(feature = "ns-wgs")]
pub mod wgs;
#[cfg(feature = "ns-xhv")]
pub mod xhv;
#[cfg(feature = "ns-xkos")]
pub mod xkos;
#[cfg(feature = "ns-xsd")]
pub mod xsd;
