// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
use crate::namespace;

namespace!(
    "http://ogp.me/ns#",;
    audio, "audio",
    audio:album, "audio:album",
    audio:artist, "audio:artist",
    audio:secure_url, "audio:secure_url",
    audio:title, "audio:title",
    audio:type, "audio:type",
    country_name, "country-name",
    description, "description",
    determiner, "determiner",
    email, "email",
    fax_number, "fax_number",
    image, "image",
    image:height, "image:height",
    image:secure_url, "image:secure_url",
    image:type, "image:type",
    image:width, "image:width",
    isbn, "isbn",
    latitude, "latitude",
    locale, "locale",
    locality, "locality",
    longitude, "longitude",
    phone_number, "phone_number",
    postal_code, "postal-code",
    region, "region",
    site_name, "site_name",
    street_address, "street-address",
    title, "title",
    type_, "type",
    upc, "upc",
    url, "url",
    video, "video",
    video:height, "video:height",
    video:secure_url, "video:secure_url",
    video:type, "video:type",
    video:width, "video:width"
);