// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
use crate::namespace;

namespace!(
    "http://www.w3.org/ns/org#",;
    ChangeEvent, "ChangeEvent",
    FormalOrganization, "FormalOrganization",
    Head, "Head",
    Membership, "Membership",
    Organization, "Organization",
    OrganizationalCollaboration, "OrganizationalCollaboration",
    OrganizationalUnit, "OrganizationalUnit",
    Post, "Post",
    Role, "Role",
    Site, "Site",
    basedAt, "basedAt",
    changedBy, "changedBy",
    classification, "classification",
    hasMember, "hasMember",
    hasMembership, "hasMembership",
    hasPost, "hasPost",
    hasPrimarySite, "hasPrimarySite",
    hasRegisteredSite, "hasRegisteredSite",
    hasSite, "hasSite",
    hasSubOrganization, "hasSubOrganization",
    hasUnit, "hasUnit",
    headOf, "headOf",
    heldBy, "heldBy",
    holds, "holds",
    identifier, "identifier",
    linkedTo, "linkedTo",
    location, "location",
    member, "member",
    memberDuring, "memberDuring",
    memberOf, "memberOf",
    organization, "organization",
    originalOrganization, "originalOrganization",
    postIn, "postIn",
    purpose, "purpose",
    remuneration, "remuneration",
    reportsTo, "reportsTo",
    resultedFrom, "resultedFrom",
    resultingOrganization, "resultingOrganization",
    role, "role",
    roleProperty, "roleProperty",
    siteAddress, "siteAddress",
    siteOf, "siteOf",
    subOrganizationOf, "subOrganizationOf",
    transitiveSubOrganizationOf, "transitiveSubOrganizationOf",
    unitOf, "unitOf"
);