// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
use crate::namespace;

namespace!(
    "http://purl.org/linked-data/cube#",;
    Attachable, "Attachable",
    AttributeProperty, "AttributeProperty",
    CodedProperty, "CodedProperty",
    ComponentProperty, "ComponentProperty",
    ComponentSet, "ComponentSet",
    ComponentSpecification, "ComponentSpecification",
    DataSet, "DataSet",
    DataStructureDefinition, "DataStructureDefinition",
    DimensionProperty, "DimensionProperty",
    HierarchicalCodeList, "HierarchicalCodeList",
    MeasureProperty, "MeasureProperty",
    Observation, "Observation",
    ObservationGroup, "ObservationGroup",
    Slice, "Slice",
    SliceKey, "SliceKey",
    attribute, "attribute",
    codeList, "codeList",
    component, "component",
    componentAttachment, "componentAttachment",
    componentProperty, "componentProperty",
    componentRequired, "componentRequired",
    concept, "concept",
    dataSet, "dataSet",
    dimension, "dimension",
    hierarchyRoot, "hierarchyRoot",
    measure, "measure",
    measureDimension, "measureDimension",
    measureType, "measureType",
    observation, "observation",
    observationGroup, "observationGroup",
    order, "order",
    parentChildProperty, "parentChildProperty",
    slice, "slice",
    sliceKey, "sliceKey",
    sliceStructure, "sliceStructure",
    structure, "structure"
);