// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
use crate::namespace;

namespace!(
    "http://www.w3.org/ns/r2rml#",;
    BaseTableOrView, "BaseTableOrView",
    BlankNode, "BlankNode",
    GraphMap, "GraphMap",
    IRI, "IRI",
    Join, "Join",
    Literal, "Literal",
    LogicalTable, "LogicalTable",
    ObjectMap, "ObjectMap",
    PredicateMap, "PredicateMap",
    PredicateObjectMap, "PredicateObjectMap",
    R2RMLView, "R2RMLView",
    RefObjectMap, "RefObjectMap",
    SQL2008, "SQL2008",
    SubjectMap, "SubjectMap",
    TermMap, "TermMap",
    TriplesMap, "TriplesMap",
    child, "child",
    class, "class",
    column, "column",
    constant, "constant",
    datatype, "datatype",
    defaultGraph, "defaultGraph",
    graph, "graph",
    graphMap, "graphMap",
    inverseExpression, "inverseExpression",
    joinCondition, "joinCondition",
    language, "language",
    logicalTable, "logicalTable",
    object, "object",
    objectMap, "objectMap",
    parent, "parent",
    parentTriplesMap, "parentTriplesMap",
    predicate, "predicate",
    predicateMap, "predicateMap",
    predicateObjectMap, "predicateObjectMap",
    sqlQuery, "sqlQuery",
    sqlVersion, "sqlVersion",
    subject, "subject",
    subjectMap, "subjectMap",
    tableName, "tableName",
    template, "template",
    termType, "termType"
);