// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
use crate::namespace;

namespace!(
    "http://semanticweb.cs.vu.nl/2009/11/sem/",;
    Actor, "Actor",
    ActorType, "ActorType",
    Authority, "Authority",
    Constraint, "Constraint",
    Core, "Core",
    Event, "Event",
    EventType, "EventType",
    Object, "Object",
    Place, "Place",
    PlaceType, "PlaceType",
    Role, "Role",
    RoleType, "RoleType",
    Temporary, "Temporary",
    Time, "Time",
    TimeType, "TimeType",
    Type, "Type",
    View, "View",
    accordingTo, "accordingTo",
    actorType, "actorType",
    eventProperty, "eventProperty",
    eventType, "eventType",
    hasActor, "hasActor",
    hasBeginTimeStamp, "hasBeginTimeStamp",
    hasEarliestBeginTimeStamp, "hasEarliestBeginTimeStamp",
    hasEarliestEndTimeStamp, "hasEarliestEndTimeStamp",
    hasEndTimeStamp, "hasEndTimeStamp",
    hasLatestBeginTimeStamp, "hasLatestBeginTimeStamp",
    hasLatestEndTimeStamp, "hasLatestEndTimeStamp",
    hasPlace, "hasPlace",
    hasSubEvent, "hasSubEvent",
    hasSubType, "hasSubType",
    hasTime, "hasTime",
    hasTimeStamp, "hasTimeStamp",
    placeType, "placeType",
    roleType, "roleType",
    subEventOf, "subEventOf",
    subTypeOf, "subTypeOf",
    timeType, "timeType",
    type_, "type"
);