// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
//! This module provides terms for `SIOC Core Ontology Namespace` vocabulary
//!
//! ## Vocabulary:
//!
//! |||
//! |-----|-----|
//! |**Title**|SIOC Core Ontology Namespace|
//! |**Prefix**|sioc|
//! |**Namespace base IRI**|[http://rdfs.org/sioc/ns#](http://rdfs.org/sioc/ns#)|
//! |**Description**|SIOC (Semantically-Interlinked Online Communities) is an ontology for describing the information in online communities.  This information can be used to export information from online communities and to link them together. The scope of the application areas that SIOC can be used for includes (and is not limited to) weblogs, message boards, mailing lists and chat channels.|
//! |**Is defined by**|[http://rdfs.org/sioc/ns#](http://rdfs.org/sioc/ns#)|
//!

use crate::namespace;

namespace!(
    "http://rdfs.org/sioc/ns#",;
    Community, "Community",
    Container, "Container",
    Forum, "Forum",
    Item, "Item",
    Post, "Post",
    Role, "Role",
    Site, "Site",
    Space, "Space",
    Thread, "Thread",
    User, "User",
    UserAccount, "UserAccount",
    Usergroup, "Usergroup",
    about, "about",
    account_of, "account_of",
    addressed_to, "addressed_to",
    administrator_of, "administrator_of",
    attachment, "attachment",
    avatar, "avatar",
    container_of, "container_of",
    content, "content",
    content_encoded, "content_encoded",
    created_at, "created_at",
    creator_of, "creator_of",
    delivered_at, "delivered_at",
    description, "description",
    discussion_of, "discussion_of",
    earlier_version, "earlier_version",
    email, "email",
    email_sha1, "email_sha1",
    embeds_knowledge, "embeds_knowledge",
    feed, "feed",
    first_name, "first_name",
    follows, "follows",
    function_of, "function_of",
    generator, "generator",
    group_of, "group_of",
    has_administrator, "has_administrator",
    has_container, "has_container",
    has_creator, "has_creator",
    has_discussion, "has_discussion",
    has_function, "has_function",
    has_group, "has_group",
    has_host, "has_host",
    has_member, "has_member",
    has_moderator, "has_moderator",
    has_modifier, "has_modifier",
    has_owner, "has_owner",
    has_parent, "has_parent",
    has_part, "has_part",
    has_reply, "has_reply",
    has_scope, "has_scope",
    has_space, "has_space",
    has_subscriber, "has_subscriber",
    has_usergroup, "has_usergroup",
    host_of, "host_of",
    id, "id",
    ip_address, "ip_address",
    last_activity_date, "last_activity_date",
    last_item_date, "last_item_date",
    last_name, "last_name",
    last_reply_date, "last_reply_date",
    later_version, "later_version",
    latest_version, "latest_version",
    likes, "likes",
    link, "link",
    links_to, "links_to",
    member_of, "member_of",
    mentions, "mentions",
    moderator_of, "moderator_of",
    modified_at, "modified_at",
    modifier_of, "modifier_of",
    name, "name",
    next_by_date, "next_by_date",
    next_version, "next_version",
    note, "note",
    num_authors, "num_authors",
    num_items, "num_items",
    num_replies, "num_replies",
    num_threads, "num_threads",
    num_views, "num_views",
    owner_of, "owner_of",
    parent_of, "parent_of",
    part_of, "part_of",
    previous_by_date, "previous_by_date",
    previous_version, "previous_version",
    read_at, "read_at",
    reference, "reference",
    related_to, "related_to",
    reply_of, "reply_of",
    respond_to, "respond_to",
    scope_of, "scope_of",
    shared_by, "shared_by",
    sibling, "sibling",
    space_of, "space_of",
    subject, "subject",
    subscriber_of, "subscriber_of",
    title, "title",
    topic, "topic",
    usergroup_of, "usergroup_of"
);
