// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
//! This module provides terms for `OWL-Time` vocabulary
//!
//! ## Vocabulary:
//!
//! |||
//! |-----|-----|
//! |**Title**|OWL-Time|
//! |**Prefix**|time|
//! |**Namespace base IRI**|[http://www.w3.org/2006/time#](http://www.w3.org/2006/time#)|
//! |**Description**||
//! |**Is defined by**|[http://www.w3.org/2006/time#](http://www.w3.org/2006/time#)|
//!

use crate::namespace;

namespace!(
    "http://www.w3.org/2006/time#",;
    2006, "2006",
    2016, "2016",
    DateTimeDescription, "DateTimeDescription",
    DateTimeInterval, "DateTimeInterval",
    DayOfWeek, "DayOfWeek",
    Duration, "Duration",
    DurationDescription, "DurationDescription",
    Friday, "Friday",
    GeneralDateTimeDescription, "GeneralDateTimeDescription",
    GeneralDurationDescription, "GeneralDurationDescription",
    Instant, "Instant",
    Interval, "Interval",
    January, "January",
    Monday, "Monday",
    MonthOfYear, "MonthOfYear",
    ProperInterval, "ProperInterval",
    Saturday, "Saturday",
    Sunday, "Sunday",
    TRS, "TRS",
    TemporalDuration, "TemporalDuration",
    TemporalEntity, "TemporalEntity",
    TemporalPosition, "TemporalPosition",
    TemporalUnit, "TemporalUnit",
    Thursday, "Thursday",
    TimePosition, "TimePosition",
    TimeZone, "TimeZone",
    Tuesday, "Tuesday",
    Wednesday, "Wednesday",
    Year, "Year",
    after, "after",
    before, "before",
    day, "day",
    dayOfWeek, "dayOfWeek",
    dayOfYear, "dayOfYear",
    days, "days",
    generalDay, "generalDay",
    generalMonth, "generalMonth",
    generalYear, "generalYear",
    hasBeginning, "hasBeginning",
    hasDateTimeDescription, "hasDateTimeDescription",
    hasDuration, "hasDuration",
    hasDurationDescription, "hasDurationDescription",
    hasEnd, "hasEnd",
    hasTRS, "hasTRS",
    hasTemporalDuration, "hasTemporalDuration",
    hasTime, "hasTime",
    hasXSDDuration, "hasXSDDuration",
    hour, "hour",
    hours, "hours",
    inDateTime, "inDateTime",
    inTemporalPosition, "inTemporalPosition",
    inTimePosition, "inTimePosition",
    inXSDDate, "inXSDDate",
    inXSDDateTime, "inXSDDateTime",
    inXSDDateTimeStamp, "inXSDDateTimeStamp",
    inXSDgYear, "inXSDgYear",
    inXSDgYearMonth, "inXSDgYearMonth",
    inside, "inside",
    intervalAfter, "intervalAfter",
    intervalBefore, "intervalBefore",
    intervalContains, "intervalContains",
    intervalDisjoint, "intervalDisjoint",
    intervalDuring, "intervalDuring",
    intervalEquals, "intervalEquals",
    intervalFinishedBy, "intervalFinishedBy",
    intervalFinishes, "intervalFinishes",
    intervalIn, "intervalIn",
    intervalMeets, "intervalMeets",
    intervalMetBy, "intervalMetBy",
    intervalOverlappedBy, "intervalOverlappedBy",
    intervalOverlaps, "intervalOverlaps",
    intervalStartedBy, "intervalStartedBy",
    intervalStarts, "intervalStarts",
    minute, "minute",
    minutes, "minutes",
    month, "month",
    monthOfYear, "monthOfYear",
    months, "months",
    nominalPosition, "nominalPosition",
    numericDuration, "numericDuration",
    numericPosition, "numericPosition",
    second, "second",
    seconds, "seconds",
    timeZone, "timeZone",
    unitDay, "unitDay",
    unitHour, "unitHour",
    unitMinute, "unitMinute",
    unitMonth, "unitMonth",
    unitSecond, "unitSecond",
    unitType, "unitType",
    unitWeek, "unitWeek",
    unitYear, "unitYear",
    week, "week",
    weeks, "weeks",
    xsdDateTime, "xsdDateTime",
    year, "year",
    years, "years"
);
