// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
//! This module provides terms for `xhv` vocabulary
//!
//! ## Vocabulary:
//!
//! |||
//! |-----|-----|
//! |**Title**||
//! |**Prefix**|xhv|
//! |**Namespace base IRI**|[http://www.w3.org/1999/xhtml/vocab#](http://www.w3.org/1999/xhtml/vocab#)|
//! |**Description**||
//! |**Is defined by**|[https://www.w3.org/2012/pyRdfa/extract?uri=https%3A%2F%2Fwww.w3.org%2F1999%2Fxhtml%2Fvocab.xhtml&format=turtle&rdfagraph=output&vocab_expansion=false&rdfa_lite=false&embedded_rdf=true&space_preserve=true&vocab_cache=true&vocab_cache_report=false&vocab_cache_refresh=false](https://www.w3.org/2012/pyRdfa/extract?uri=https%3A%2F%2Fwww.w3.org%2F1999%2Fxhtml%2Fvocab.xhtml&format=turtle&rdfagraph=output&vocab_expansion=false&rdfa_lite=false&embedded_rdf=true&space_preserve=true&vocab_cache=true&vocab_cache_report=false&vocab_cache_refresh=false)|
//!

use crate::namespace;

namespace!(
    "http://www.w3.org/1999/xhtml/vocab#",;
    alert, "alert",
    alertdialog, "alertdialog",
    alternate, "alternate",
    appendix, "appendix",
    application, "application",
    article, "article",
    banner, "banner",
    bookmark, "bookmark",
    button, "button",
    chapter, "chapter",
    checkbox, "checkbox",
    cite, "cite",
    columnheader, "columnheader",
    combobox, "combobox",
    complementary, "complementary",
    contentinfo, "contentinfo",
    contents, "contents",
    copyright, "copyright",
    definition, "definition",
    dialog, "dialog",
    directory, "directory",
    document, "document",
    first, "first",
    glossary, "glossary",
    grid, "grid",
    gridcell, "gridcell",
    group, "group",
    heading, "heading",
    help, "help",
    icon, "icon",
    img, "img",
    index, "index",
    itsRules, "itsRules",
    last, "last",
    license, "license",
    link, "link",
    list, "list",
    listbox, "listbox",
    listitem, "listitem",
    log, "log",
    main, "main",
    marquee, "marquee",
    math, "math",
    menu, "menu",
    menubar, "menubar",
    menuitem, "menuitem",
    menuitemcheckbox, "menuitemcheckbox",
    menuitemradio, "menuitemradio",
    meta, "meta",
    navigation, "navigation",
    next, "next",
    note, "note",
    option, "option",
    p3pv1, "p3pv1",
    presentation, "presentation",
    prev, "prev",
    progressbar, "progressbar",
    radio, "radio",
    radiogroup, "radiogroup",
    region, "region",
    relrev_properties, "relrev-properties",
    role, "role",
    role_properties, "role-properties",
    row, "row",
    rowheader, "rowheader",
    search, "search",
    section, "section",
    separator, "separator",
    slider, "slider",
    spinbutton, "spinbutton",
    start, "start",
    status, "status",
    stylesheet, "stylesheet",
    subsection, "subsection",
    tab, "tab",
    tablist, "tablist",
    tabpanel, "tabpanel",
    textbox, "textbox",
    timer, "timer",
    toolbar, "toolbar",
    tooltip, "tooltip",
    top, "top",
    tree, "tree",
    treegrid, "treegrid",
    treeitem, "treeitem",
    up, "up"
);
