// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
use crate::namespace;

namespace!(
    "http://rdf-vocabulary.ddialliance.org/xkos#",;
    ClassificationLevel, "ClassificationLevel",
    ConceptAssociation, "ConceptAssociation",
    Correspondence, "Correspondence",
    ExplanatoryNote, "ExplanatoryNote",
    additionalContentNote, "additionalContentNote",
    after, "after",
    before, "before",
    belongsTo, "belongsTo",
    caseLaw, "caseLaw",
    causal, "causal",
    causedBy, "causedBy",
    causes, "causes",
    classifiedUnder, "classifiedUnder",
    compares, "compares",
    coreContentNote, "coreContentNote",
    covers, "covers",
    coversExhaustively, "coversExhaustively",
    coversMutuallyExclusively, "coversMutuallyExclusively",
    depth, "depth",
    disjoint, "disjoint",
    exclusionNote, "exclusionNote",
    follows, "follows",
    generalizes, "generalizes",
    hasPart, "hasPart",
    inclusionNote, "inclusionNote",
    isPartOf, "isPartOf",
    levels, "levels",
    madeOf, "madeOf",
    maxLength, "maxLength",
    next, "next",
    notationPattern, "notationPattern",
    numberOfLevels, "numberOfLevels",
    organizedBy, "organizedBy",
    plainText, "plainText",
    precedes, "precedes",
    previous, "previous",
    sequential, "sequential",
    sourceConcept, "sourceConcept",
    specializes, "specializes",
    succeeds, "succeeds",
    supersedes, "supersedes",
    targetConcept, "targetConcept",
    temporal, "temporal",
    variant, "variant"
);