// THIS FILE IS GENERATED. ONE SHOULD NOT MODIFY IT
use crate::namespace;

namespace!(
    "http://www.w3.org/2001/XMLSchema#",;
    ENTITIES, "ENTITIES",
    ENTITY, "ENTITY",
    ID, "ID",
    IDREF, "IDREF",
    IDREFS, "IDREFS",
    NCName, "NCName",
    NMTOKEN, "NMTOKEN",
    NMTOKENS, "NMTOKENS",
    NOTATION, "NOTATION",
    Name, "Name",
    QName, "QName",
    anyAtomicType, "anyAtomicType",
    anySimpleType, "anySimpleType",
    anyType, "anyType",
    anyURI, "anyURI",
    base64Binary, "base64Binary",
    boolean, "boolean",
    byte, "byte",
    date, "date",
    dateTime, "dateTime",
    dateTimeStamp, "dateTimeStamp",
    dayTimeDuration, "dayTimeDuration",
    decimal, "decimal",
    double, "double",
    duration, "duration",
    float, "float",
    gDay, "gDay",
    gMonth, "gMonth",
    gMonthDay, "gMonthDay",
    gYear, "gYear",
    gYearMonth, "gYearMonth",
    hexBinary, "hexBinary",
    int, "int",
    integer, "integer",
    language, "language",
    long, "long",
    negativeInteger, "negativeInteger",
    nonNegativeInteger, "nonNegativeInteger",
    nonPositiveInteger, "nonPositiveInteger",
    normalizedString, "normalizedString",
    positiveInteger, "positiveInteger",
    short, "short",
    string, "string",
    time, "time",
    token, "token",
    unsignedByte, "unsignedByte",
    unsignedInt, "unsignedInt",
    unsignedLong, "unsignedLong",
    unsignedShort, "unsignedShort",
    yearMonthDuration, "yearMonthDuration"
);