[package]
name = "rdf_vocabularies"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = {version = "1.9.0", optional = true}
# 0.7.1 seems not working with stable toolchain. due to mownstr bug. Till that fixed.
sophia_api = {version = "=0.7.0", optional = true}
sophia_turtle = {version = "=0.7.0", optional = true}
sophia_rio = {version = "=0.7.0", optional = true}
sophia_inmem = {version = "=0.7.0", optional = true}
rio_turtle = {version = "0.6.1", optional = true}
mownstr = {version = "=0.1.1", optional = true}



[features]
default = ["ns", "dataset", "vocab-rdf", "vocab-rdfs", "vocab-xsd"]
ns = []
dataset = ["once_cell", "sophia_api", "sophia_turtle", "sophia_rio", "sophia_inmem", "rio_turtle", "mownstr"]
vocab-acl = []
vocab-as = []
vocab-bibo = []
vocab-cc = []
vocab-cnt = []
vocab-constant = []
vocab-csvw = []
vocab-dash = []
vocab-dbo = []
vocab-dc11 = []
vocab-dcam = []
vocab-dcat = []
vocab-dcmitype = []
vocab-dcterms = []
vocab-discipline = []
vocab-doap = []
vocab-dpv = []
vocab-dqv = []
vocab-dtype = []
vocab-duv = []
vocab-earl = []
vocab-ebucore = []
vocab-exif = []
vocab-foaf = []
vocab-frbr = []
vocab-geof = []
vocab-geo = []
vocab-geor = []
vocab-gn = []
vocab-grddl = []
vocab-gr = []
vocab-gs1 = []
vocab-gtfs = []
vocab-http = []
vocab-hydra = []
vocab-ical = []
vocab-ldp = []
vocab-locn = []
vocab-lvont = []
vocab-ma = []
vocab-oa = []
vocab-og = []
vocab-org = []
vocab-owl = []
vocab-prefix = []
vocab-prov = []
vocab-qb = []
vocab-qkdv = []
vocab-quantitykind = []
vocab-qudt = []
vocab-rdau = []
vocab-rdfa = []
vocab-rdf = []
vocab-rdfs = []
vocab-rico = []
vocab-rr = []
vocab-rss = []
vocab-schema = []
vocab-sdmx = []
vocab-sd = []
vocab-sem = []
vocab-shex = []
vocab-sh = []
vocab-sioc = []
vocab-skos = []
vocab-skosxl = []
vocab-sosa = []
vocab-sou = []
vocab-ssn = []
vocab-test = []
vocab-time = []
vocab-unit = []
vocab-vaem = []
vocab-vann = []
vocab-vcard = []
vocab-void = []
vocab-vs = []
vocab-wgs = []
vocab-xhv = []
vocab-xkos = []
vocab-xsd = []

[dev-dependencies]
claim = "0.5.0"
